server:
    port: 8765
spring:
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    # lower-case-service-id: true

    main:
        allow-circular-references: true
