server:
    port: 8000
spring:
    datasource:
        password: Srinu@160489
        url: jdbc:mysql://localhost:3306/product_service
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true